name: "Deploy scripts"
description: "Application that deploys data models to tanants"
author: "talent::digital"

inputs:
  testing_inputs:
    description: "lorem ipsum"
    required: true

runs:
  using: "node16"
  main: "./dist/index.js"
