name: Canary

on:
  push:
    # paths:
    #   - "apps/canary/**"
    branches: ["feature/TI-2015-deploy-scripts-github-actions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-metadata:
    runs-on: ubuntu-latest
    name: Deploy metadata
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy season metadata
        uses: ./deploy-scripts
        env:
          Action_Rooth_Path: "apps/canary/"
          EPISODES_PROVISIONER_CLIENT_PASSWORD: ${{ secrets.EPISODES_PROVISIONER_CLIENT_PASSWORD }}
