name: Deploy Season
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: talent-digital/deploy-season@v1
        with:
          environment_name: "devtd2"
          episodes_provisioner_client_password: ${{ secrets.EPISODES_PROVISIONER_CLIENT_PASSWORD }}
          episodes_provisioner_client: "episodes-provisioner-client"
          target_domain: "talentdigit.al"
          season_file_path: "apps/canary/src"
