name: Lint, unit tests & e2e tests

on:
  pull_request:
    branches: ["main"]

jobs:
  lint-build-run-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Dependencies in root folder
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          working-directory: apps/canary-snippet-integration
          start: npm run dev
        env:
          WEB_USERNAME: ${{ secrets.CYPRESS_WEB_USERNAME}}
          WEB_PASSWORD: ${{secrets.CYPRESS_WEB_PASSWORD}}

      - name: Archive cypress video web
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: cypress-video
          path: apps/canary-snippet-integration/cypress/videos/**/*.mp4
          retention-days: 30
